### ISSUE TITLE
Removing the twitter username from UI

### ISSUE THREAD

**Issue by iatharva** [Skyhero-admin/Skyhero-admin.github.io#4]
Just a suggestion.

I think if you remove your @username from the UI where there are social media links, then all three links would look good and properly aligned

You might have added the @username intentionally so that people would directly be aware of your username. But I think there is no need for it if it's already a link to your twitter.

**Comment by Skyhero-admin** [comment]
I guess it would look more even if I remove the @username :sweat_smile: 
Thanks for the suggestion I will fix it :+1:

**Comment by iatharva** [comment]
Happy to help!

**Comment by Skyhero-admin** [comment]
I have fixed it now :grin:
